apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: java-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      containers:
      - name: java-hello-world
        image: arvindockerregistry.azurecr.io/java-hello-world:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: java-hello-world
