apiVersion: v1
kind: Pod
metadata:
  name: java-hello-world
  labels:
    name:  hello
spec:
  containers:
  - image: arvindockerregistry.azurecr.io/java-hello-world:latest
    imagePullPolicy: Always
    name: ratings-web
    resources:
      requests:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 8080
      name: http-web
      protocol: TCP
