# basic service + deployment
apiVersion: v1
kind: Service
metadata:
  name: java-hello-world
  labels:
    app: java-hello-world-v1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: java-hello-world-v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-hello-world-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-hello-world-v1
    spec:
      containers:
      - name: java-hello-world
        image: arvindockerregistry.azurecr.io/java-hello-world:latest
        ports:
        - containerPort: 8080
